"""add is_biometric_verified to users

Revision ID: 5c3fc03fd784
Revises: 42a1cddb263b
Create Date: 2025-10-29 19:18:28.033348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c3fc03fd784'
down_revision: Union[str, None] = '42a1cddb263b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_biometric_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_biometric_verified')
    # ### end Alembic commands ###
